### ISSUE TITLE
Determine strategy for nested values in data dictionaries

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoblacklight_admin#113]
Many data dictionaries are simple flat tables of field names and definitions. However, some have more complex schemas where certain fields have their own codebooks.

Here is an example: https://resources.gisdata.mn.gov/pub/gdrs/data/pub/us_mn_co_rice/loc_addresses/metadata/metadata.html

How might we store a table like this?

**Comment by karenmajewicz** [comment]
This example does not include a data dictionary, but more of a codebook: https://resources.gisdata.mn.gov/pub/gdrs/data/pub/us_mn_state_dnr/biota_landcover_landsat_tm_1990/metadata/metadata.html

What would our strategy be for this?

**Comment by ewlarson** [comment]
Hmmm... these examples are a bit complex. And an external distribution link of "Documentation (external)" type won't suffice here?

If that is indeed the case, I think we'd want to store/capture the webpage (HTML) here.

Options:
1. Have Wayback Machine archive it, using something like: https://github.com/buren/wayback_archiver
2. Add an optional "asset" uploader to the DataDictionary model for uploading (HTML file, or a zip file, maybe PDFs, etc.)

**Comment by karenmajewicz** [comment]
I think assigning this as Documentation link and/or saving the HTML page would work. I am kind of exploring the limits of what we can store in a structured way to provide users with more consistent ways to understand the data content.

**Comment by karenmajewicz** [comment]
For now, nested values can be described or accessed via a link from within the cell. We can also create a standalone file assigned to the Documentation reference key.
