### ISSUE TITLE
Unable to login after starting server

### ISSUE THREAD

**Issue by yalamber** [geobtaa/geoblacklight_admin#14]
Hello, 
I setup the application as provided instructions. I am able to see login screen
When trying to access admin panel I am redirected to signin link http://127.0.0.1:3000/users/sign_in
but when I try to login it shows Invalid Email or password message
<img width="1187" alt="Screenshot 2023-10-10 at 08 33 07" src="https://github.com/geobtaa/geoblacklight_admin/assets/361022/32af265b-2410-4e33-ae52-74155bfa819e">

**Comment by ewlarson** [comment]
Hello!

If the database has been seeded, there should be a default user/password: admin@geoblacklight.org / 123456

Try running: bundle exec rake db:seed

Hopefully that does it.

**Comment by yalamber** [comment]
@ewlarson worked after running migration and seed Thank you
