### ISSUE TITLE
SVG Icon - In production mode GBL Admin looks awkward due to a missing bookmark icon

### ISSUE THREAD

**Issue by ewlarson** [geobtaa/geoblacklight_admin#18]
```html
<!-- SVG file not found: 'bookmark-regular.svg' -->
```

<img width="1723" alt="Screenshot 2023-10-13 at 4 20 21 PM" src="https://github.com/geobtaa/geoblacklight_admin/assets/69827/dc09f244-10ca-4934-bafd-27cc85371cec">

**Comment by yalamber** [comment]
Hello @ewlarson, 
I just noticed this in one of our setup of this application. If I have to add this fix in to our server, do we just update the gem and would it work as expected by doing new build? Or what should appropriate approach be here to add this fix to our production apps.
