### ISSUE TITLE
Is it possible to sync changes made to solr directly?

### ISSUE THREAD

**Issue by yalamber** [geobtaa/geoblacklight_admin#25]
Hello, 
We have added some data to solr directly, Is it possible to sync those documents in the geoblacklight admin?
Right now we see Database is missing document  error on those records.

**Comment by ewlarson** [comment]
Hi! I'm sorry for any confusion, but you need your data to flow from the database and into Solr. The database records are your canonical data and Solr is just an index for discovery.

If you run any CSV Export from GBL Admin, that file will show you the CSV headers you'll need to import data into the database. Hopefully you can convert your Solr docs into a CSV file with similar headers for import into the database.
