### ISSUE TITLE
Troubleshoot publication state, filtering, and sort combinations.

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoblacklight_admin#31]
One of the facets in Admin is "Publication State".  We use this frequently to isolate items that are currently published but need to be unpublished/retired.

I am seeing some odd behavior though where "Unpublished" items are showing up in the published.  Try this:

1. Select Accrual Method = ArcGIS Hub
2. Select Publication State = published
3. Sort by = Oldest first

When I follow these three steps, the results at the top are "Unpublished" items.  This URL query may replicate those results: https://geo.btaa.org/admin/documents?f%5Bb1g_dct_accrualMethod_s%5D%5B%5D=ArcGIS+Hub&f%5Bb1g_publication_state_s%5D%5B%5D=published&rows=20&sort=date_modified_dtsi+asc

**Comment by ewlarson** [comment]
I cannot replicate locally using a small dataset. I wonder if Solr and the Database have become out of sync. I'll reindex the production database into Solr and see if that resolves this issue.

**Comment by ewlarson** [comment]
These records have bad bounding boxes, which save to the database, but do not index into Solr as expected. We need better validation for bboxes.
