### ISSUE TITLE
Add "Date Accessioned" field to Admin facets under Publication State

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoblacklight_admin#32]
When we reharvest from data portals, we create a fresh list of current datasets.  We then upload them to GBL Admin and publish them.

Then, we then need to isolate the the outdated records and unpublish them. To do so, we check the "Date Accessioned" field. It would be easier to find and unpublish them if the Date Accessioned field were a facet right under the Publication State.

**Comment by ewlarson** [comment]
We want to make faceting configurable.

**Comment by ewlarson** [comment]
Okay... this is a lot harder than originally imagined. The values in that field are not normalized.

Examples:
* ["20230929"]
* ["2018-12-07"]
* ["8/31/20"]
* [""]
* []
* ["2019", "2021-04-27", "2022-10-27"]

Screenshot
![Screenshot 2023-12-05 at 1 20 36 PM](https://github.com/geobtaa/geoblacklight_admin/assets/69827/9b161274-d9f9-46c8-bf10-b1d024b06c26)

Unfortunately, the field is just a multi-valued string, with no sanity checking/control.

**Comment by ewlarson** [comment]
Some steps to move ahead:

1. Write a database migration to cleanse the data already captured
2. Change this element's type to a date
3. Use a placeholder / inputmask solution to guide the right data on entry (YYYY-MM-DD)
4. Add a validation step for the data (ensure it's a proper date)

**Comment by karenmajewicz** [comment]
I normalized the records so that they are all single values of yyyy-mm-dd or blank.  Our newer harvesting scripts automatically insert these values, so most of the records were already in that format. https://geo.btaa.org/admin/blazer/queries/43-accessioned-dates

Another thing to consider here is the idea we had to automatically tag imports with some kind of generated accession code. That is main purpose of these dates - to be able to differentiate between successive uploads.

**Comment by karenmajewicz** [comment]
The various date/tracking fields we use:

Internal Metadata:

- `created_at`: Generated by GBL Admin and tracking the 1st time an ID was created/uploaded
- `updated_a`t: Generated by GBL Admin and tracking whenever a record was changed, either through CSV upload or manual edit.

Kithe Model:

- `b1g_dateAccessioned_sm`: Part of the B1G profile of Aardvark for keeping track of harvest cycles. This reflects batches/uploads of a harvest/reharvest. It may or may not match `created_at` or `updated_at`.

**Comment by karenmajewicz** [comment]
Adding to Advanced Search: https://github.com/geobtaa/geoportal/issues/552
