### ISSUE TITLE
GBL Admin stalls when I try to change the Publication State on a large number of items

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoblacklight_admin#33]
I tried to Unpublish ~10,000 items and got the "We're sorry, but something went wrong" error. I tried it again after about 30 minutes, but got the same error. I don't know if this showed up in the logs, so reporting it here.

**Comment by karenmajewicz** [comment]
Steps:

1. Select Accrual Method = ArcGIS Hubs
2. Select all results
3. Change Publication State to Unpublished

error!

**Comment by ewlarson** [comment]
In the example above, our Bulk Action instance is ultimately created:
https://geodev.btaa.org/admin/bulk_actions/35

It's just that the application spins for ~60s and times itself out while generating the parent/wrapping Bulk Action of 14K subactions. The request to create the primary Bulk Action needs to return immediately and not "block" itself while creating each individual BulkActionJob within itself.

Hope that makes sense. Definitely something to polish up.

**Comment by karenmajewicz** [comment]
OK, the app does not stall out anymore, but it does take a long time for the docs to load in the Bulk Action page. We may want to document this behavior for any adopters.
