### ISSUE TITLE
Update field definitions

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoblacklight_admin#40]
We have a custom domain for our GitHub static sites now, so the base URL for our metadata documentation is gin.btaa.org instead of geobtaa.github.io.  To do:

- [x] Manually change the values on the elements page https://geodev.btaa.org/admin/elements
- [x] Request a server restart
- [x] Do the same on geo.btaa.org/admin/elements

**Comment by karenmajewicz** [comment]
@ewlarson - we updated the field definitions and are ready for server restarts on both dev and prod.

**Comment by ewlarson** [comment]
Closing. I've started both puma and sidekiq on each of our servers. You should be all set now.
