### ISSUE TITLE
Incorrect messages in Multiple Download links uploads/deletes

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoblacklight_admin#41]
See https://github.com/geobtaa/metadata/issues/542

We are getting error messages when uploading or deleting CSVs for multiple downloads. This seems to occur when a record already has multiple downloads attached.

1. If we try to upload additional links, it says `Document Links could not be created.`
2. If we upload a file for deleting links, it says `Download Links could not be destroyed.`

However, when we look at the record, we see that these actions are successful.

**Comment by ewlarson** [comment]
FYI, the application code for Multiple Download Links and Institutional Access Links is almost identical. The same type of error will be thrown for Institutional Access Links, too.

**Comment by karenmajewicz** [comment]
Tested importing new multiple downloads to dev, but it threw a Rails error. The links did import though.

**Comment by ewlarson** [comment]
^ Can you share the CSV file that tossed the error?

**Comment by karenmajewicz** [comment]
It was this one 
[05a-01_multiple-downloads.csv](https://github.com/geobtaa/geoblacklight_admin/files/14465163/05a-01_multiple-downloads.csv)
