### ISSUE TITLE
Add reference URIs for PMTiles and COGS

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoblacklight_admin#48]
GBL version 4.4 supports PM Tiles and COGS, but we have not enabled them in our workflows yet.

Here are the labels and URIs:

PMTiles: https://github.com/protomaps/PMTiles
COG: https://github.com/cogeotiff/cog-spec

To do:

- [x] add to form view under references in GBL Admin
- [x] add to import and export templates

**Comment by karenmajewicz** [comment]
I pulled the GBL fixtures and found these new ones as well:

'https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames': 'XYZ Tiles',
'http://www.opengis.net/def/serviceType/ogc/wmts': 'WMTS',
'https://github.com/mapbox/tilejson-spec': 'TileJSON',
'https://wiki.osgeo.org/wiki/Tile_Map_Service_Specification': 'Tile Map Service'

I am not sure if we need all of these, but they are part of the fixtures now.

**Comment by ewlarson** [comment]
Added to GBL v4.4 support branch #47

**Comment by ewlarson** [comment]
These are all on GeoDev now.
