### ISSUE TITLE
Status message for Bulk Actions never changes from "queued"

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoblacklight_admin#51]
On the Bulk Action show page, there are two boxes at the top. One shows the number of documents selected and the second is just called "Bulk Action." This second box starts off with a button "Run Bulk Action." Once the user clicks it, it changes to "queued."  This message never changes even after the action is done.

I think it used to change to "done"?

**Comment by ewlarson** [comment]
Closing as I  did address this in a prior sprint.

See the "complete" status in the image below:
![Image](https://github.com/user-attachments/assets/bd799ff9-60bd-4f0e-9789-11aea63f5474)
