### ISSUE TITLE
Batch deletion of Insitutional Access links returns error

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoblacklight_admin#58]
Actions performed:

1. Went to Insitutional Access links dashboard https://geo.btaa.org/admin/access
2. Clicked `-Delete CSV`
3. Uploaded a CSV of links to be deleted.
[sanborn-delete.csv](https://github.com/user-attachments/files/15920007/sanborn-delete.csv)
4. Application returned:

`500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.`

5. Spot checked several records and the links have been deleted from GBL Admin. (ex: https://geo.btaa.org/admin/documents/999-0011-kentucky/access).   Both the U. of Illinois and Maryland links are gone
6. Checked the front end: https://geo.btaa.org/catalog/999-0011-kentucky. The deleted links are still present in Solr.

**Comment by karenmajewicz** [comment]
Related AppSignal error:

`undefined local variable or method "document_accesses_path" for an instance of Admin::DocumentAccessesController`

**Comment by karenmajewicz** [comment]
Employed a workaround:

1. deleted the primary records affected, which removed the access links.
2. did a fresh import of the same records
3.  did a new upload of all the access links.
     This produced : `We're sorry, but something went wrong. If you are the application owner check the logs for more information.`. However, like this issue #41 , the links **did** import

Updated collection here: https://geo.btaa.org/?f%5Bb1g_geom_import_id_ssi%5D%5B%5D=189&page=1&per_page=10&publication_state=published

**Comment by ewlarson** [comment]
I tested this locally and it just worked for me. I also fixed the `document_accesses_path` routing error. Next time you encounter any issues like this, ping me so we can troubleshoot before going down the work around route.

**Comment by ewlarson** [comment]
Closing for now as I cannot replicate locally. Reopen if another issue comes forth.
