### ISSUE TITLE
Add Northwestern University to Access Links

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoblacklight_admin#59]
Add 

"15" => "Northwestern University"

https://github.com/geobtaa/geoblacklight_admin/blob/ecb10bc2f175bf943fb903f179450260a65b6fbe/app/helpers/geoblacklight_admin_helper.rb#L56

and 

https://github.com/geobtaa/geoblacklight_admin/blob/ecb10bc2f175bf943fb903f179450260a65b6fbe/test/helpers/geoblacklight_admin_helper_test.rb#L52

**Comment by ewlarson** [comment]
Added NW to GeoDev. Will make GeoProd on next release.

![Image](https://github.com/geobtaa/geoblacklight_admin/assets/69827/f42277cf-2774-4cb5-940d-d4a20a598b26)
