### ISSUE TITLE
Harvest thumbnails using IIIF Manifest APIs

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoblacklight_admin#65]
Our current thumbnail harvesting code will harvest from IIIF Image APIs.  It would be nice to enhance this to also harvest from IIIF Presentation (Manifest) APIs.  Since Manifests are often multipart, we should just harvest the first image listed.

**Comment by ewlarson** [comment]
**Indiana** - No IIIF Manifests (that I know of)

**Illinois** - IIIF Manifests have thumbnail entries
ex. https://digital.library.illinois.edu/items/a07f9c70-994e-0134-2096-0050569601ca-8/manifest

**Iowa** - No IIIF Manifests (that I know of)

**Maryland** - No IIIF Manifests (that I know of)

**Michigan** - IIIF Manifests have thumbnail entries
ex. https://quod.lib.umich.edu/cgi/i/image/api/search/clark1ic:003287878

**Michigan State** - 
ex. https://d.lib.msu.edu/maps/1084/manifest

**Minnesota**
ex. https://cdm16022.contentdm.oclc.org/iiif/info/p16022coll205/265/manifest.json

**Nebraska** - 
ex. https://mediacommons.unl.edu/luna/servlet/iiif/m/RUMSEY~8~1~317895~90086920/manifest

**Northwestern** - 
ex. https://api.dc.library.northwestern.edu/api/v2/works/183249d3-aff6-40d5-b445-8f70addedcc3?as=iiif

**Ohio State** - IIIF Manifests do not have thumbnail entries
ex. https://library.osu.edu/dc/concern/generic_works/9k41zr126/manifest

**Penn State** - 
ex. https://digital.libraries.psu.edu/iiif/2/maps1:30183/manifest.json

**Rutgers** - No IIIF Manifests (that I know of)

**Comment by karenmajewicz** [comment]
It looks like Maryland might have manifests. Inspecting the page for [this record](https://digital.lib.umd.edu/resultsnew/id/umd:82079), I found:

Image: https://iiif.lib.umd.edu/images/fedora2:umd:82080/info.json
Presentation: https://iiif.lib.umd.edu/manifests/fedora2:umd:82079/manifest

**Comment by ewlarson** [comment]
Nice find! You can leave the Image API values in there. IIIF Manifests are prioritized over IIIF API.

**Comment by ewlarson** [comment]
Initial `iiif_manifest` viewer and images service thumbnail code is running on GeoProd now.
