### ISSUE TITLE
A record with assets is causing the text search in Dev Admin to break

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoblacklight_admin#66]
Edit: This record is causing the search to error: https://geodev.btaa.org/catalog/997a6f44-a44f-4397-af67-c224833546d3
I can view it in the geoportal and via direct entry into Admin. However, using a search parameter that returns it causes Admin to error.

The text search box in Dev Admin frequently returns `500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.`

Some of the filters in the Advanced Search work (i.e. Resource Class), but others are broken (i.e. Provider).

I think there might be a corrupt record somewhere, but I am not sure how to find it.

**Comment by karenmajewicz** [comment]
Searching for records with the Provider Big Ten Academic Alliance are causing this error.

https://geodev.btaa.org/admin/documents?q=big+ten+academic+alliance

**Comment by karenmajewicz** [comment]
I think this has something to do with the Assets.  AppSignal shows an error for this of `ActiveStorage::FileNotFoundError`. I have been playing around with uploading and deleting files using this collection https://geodev.btaa.org/catalog/btaa-074bc4ad-ed3d-4fe7-8339-562bc1109cb3

I see that [this record](https://geodev.btaa.org/admin/documents/d6ea0892-585b-4573-932d-e893a8216968/edit) may have a problem. On the main item edit page, it shows 1 additional asset. However, when I go to the Document - Assets page, none are present. Maybe there is something amiss with deleting assets?

**Comment by karenmajewicz** [comment]
I narrowed down the problem record: https://geodev.btaa.org/catalog/997a6f44-a44f-4397-af67-c224833546d3

#

**Comment by ewlarson** [comment]
Link displaying fix on GeoDev:
https://geodev.btaa.org/admin/documents?q=Big+Ten+Academic+Alliance+
