### ISSUE TITLE
Enable multiple downloads in the asset upload interface

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoblacklight_admin#70]
The current interface allows the user to upload an asset and select a References URI.  However, for multiple downloads, we still need to assign a label.  Could this be added to the upload interface? 

Related to #69

**Comment by ewlarson** [comment]
Label can be assigned after upload in the Asset#edit view.

**Comment by karenmajewicz** [comment]
Solved with new asset panel interface
