### ISSUE TITLE
Delete missing document from production

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoblacklight_admin#71]
We have a Solr doc here that needs to be deleted: https://geo.btaa.org/catalog/sup as it is not in GBL Admin.

Any ideas how this record got in Solr, but is missing from GBL Admin?  It seems to be a duplicate of this: https://geo.btaa.org/catalog/1414-0000001

**Comment by ewlarson** [comment]
New GBL Admin rake task: 
`rake geoblacklight_admin:solr:delete_orphans`
