### ISSUE TITLE
Enable editing for reference URI type in Additional Assets panel

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoblacklight_admin#74]
The Additional Assets panel features an editing view.  Using the dropdown, I can change the Reference URI Type. This change will save in GBL Admin, but does not appear to get pushed to Solr.

Example: https://geodev.btaa.org/admin/documents/sample-for%20workflowing/assets

**Comment by ewlarson** [comment]
Closing. There is an after_save callback on an Asset that will reindex the parent object now.
