### ISSUE TITLE
Refine dropdown References list on Assets- Add files screen

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoblacklight_admin#78]
Currently, the dropdown loads the full References list. However, many of these are not relevant to file uploads.  To keep:

- Cloud Optimized GeoTIFF (COG)
- Data Dictionary / documentation download
- Direct Download file
- Metadata in FGDC
- Metadata in HTML
- Metadata in ISO 19139
- Metadata in MODS
- OpenIndexMap
- PMTiles
- Thumbnail file ??

**Comment by ewlarson** [comment]
Thumbnail file... I'd prefer the application derive the thumbnails, with the biggest image we can obtain being added as an additional asset as an "Image file".

**Comment by ewlarson** [comment]
![Image](https://github.com/user-attachments/assets/42b204f2-0836-4974-aa6a-e372e760ec1d)

**Comment by karenmajewicz** [comment]
Looks great. Could you make some minor label changes:

 "Data Dictionary / documentation download" to "**Data Dictionary / documentation**"
"Direct download file" to "**Download**"
