### ISSUE TITLE
Determine if changing Reference type causes problems.

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoblacklight_admin#79]
I broke a record and am not sure why.

 https://geodev.btaa.org/admin/documents/btaa-1bbf2981131345819fb9874b965fd23c/edit

Steps:

- Tried to upload a multipage HTML file and assigned it to the Data Dictionary/Documentation.  
- I checked in in the interface. The record is viewable, but when I clicked "Documentation," I got a disallowed file error
- Deleted the HTML
- Uploaded an Excel file and assigned to Data Dictionary/Documentation.
- The record is now broken with a 500 error.

**Comment by ewlarson** [comment]
Yeah, seems like two issues related to "Documentation" here really...

1) The files — the multipage HTML file, Excel file
2) AWS S3 permissions — why are we seeing the AWS "AccessDenied" error

If you have them around, could you please attach each of those files (HTML and Excel) to this ticket for troubleshooting?

The permissions issue is a little more complicated, as I no longer have access to the AWS S3 management console. I've written Michael asking for both of us to have access to the management console to troubleshoot these type of file access issues.

**Comment by karenmajewicz** [comment]
This was the xlsx file: [AddressOneSTREET_CENTERLINES_DataDictionary05282019.xlsx](https://github.com/user-attachments/files/16936309/AddressOneSTREET_CENTERLINES_DataDictionary05282019.xlsx)

**Comment by ewlarson** [comment]
Removed the bad reference link and re-added the XLSX file. Everything is working as expected now. If this happens again we should review the background queue for failures or backlog.

Closing this ticket
